
function dydt = diffeq(t, y)

global param totalTAK totalIKK;

dydt=zeros(4,1);

%get signal value
signal1=libPulseDelay(t);


uTAK1=(totalTAK-y(1));
uIKK1=(totalIKK-y(2)-y(3)-y(4));

uTAK2=y(1);
uIKK2=y(2);
uIKK3=y(3);
uIKK4=y(4);

rTAK2 = -param.pTAK.k6t*uTAK2/(param.pTAK.k6m + uTAK2) + ...
     (param.pTAK.k5ta+param.pTAK.MALT1+param.pTAK.TRAF6)*signal1*uTAK1/(param.pTAK.k5ma + uTAK1) + ...
     param.pTAK.k5tb2*(uIKK2)*uTAK1/(param.pTAK.k5mb2 + uTAK1) + ...
     param.pTAK.k5tb3*(uIKK3)*uTAK1/(param.pTAK.k5mb3 + uTAK1) + param.pTAK.k5z*uTAK1;

rIKK2 = ...
    (param.pIKK1.k1ta+param.pIKK1.TRAF6)*uTAK2*uIKK1/(param.pIKK1.k1ma + uIKK1) - ...
     param.pIKK1.k1tb*uIKK2/(param.pIKK1.k1mb + uIKK2) - ...
     param.pIKK2.k2ta*uIKK2/(param.pIKK2.k2ma + uIKK2) - ...
     param.pIKK2.k2tb*uIKK2*uIKK3/(param.pIKK2.k2mb + uIKK2) + ...
     param.pIKK2.k2tc*uIKK3/(param.pIKK2.k2mc + uIKK3);
rIKK3 = ...
    param.pIKK2.k2ta*uIKK2/(param.pIKK2.k2ma + uIKK2) + ...
     param.pIKK2.k2tb*uIKK2*uIKK3/(param.pIKK2.k2mb + uIKK2) - ...
     param.pIKK3.k3t*uIKK3/(param.pIKK3.k3m + uIKK3) - param.pIKK2.k2tc*uIKK3/(param.pIKK2.k2mc + uIKK3);
rIKK4 = ...
    param.pIKK3.k3t*uIKK3/(param.pIKK3.k3m + uIKK3) - param.pIKK3.k4t*uIKK4/(param.pIKK3.k4m + uIKK4);

dydt = [rTAK2; rIKK2; rIKK3; rIKK4];
